services: 
  backend_app:
    build: ./backend
    container_name: backend_app_container
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "4000:4000"
    #env_file:
    #  - ./backend/.env
    environment:
      DATABASE_URL: "postgresql://postgres:EstudoTeste2025@postgres:5432/backend"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: backend
      DB_USER: postgres
      DB_PASSWORD: "EstudoTeste2025"
      JWT_SECRET: "MinhaJWTSecretSuperForte"
    depends_on:
      - postgres
    networks:
      - backend
  postgres:
    image: postgres:latest
    container_name: postgres_db_container
    #env_file:
    #  - ./backend/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "EstudoTeste2025"
      POSTGRES_DB: backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
