
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nodejs-backend'
    static_configs:
      - targets: ['backend_app:4000']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
